export const GOLD_LIST = [
  "123 Playground",
  "A Pirate's Adventure",
  "A Pirate's Adventure ~ Treasures of the Seven Seas",
  "Acme Fun Factory",
  "Additional Peppa Pig World Characters Meet & Greet",
  "Advanced Training Lab",
  "Adventure Playground",
  "Adventure River",
  "Adventureland Treehouse inspired by Walt Disney’s Swiss Family Robinson",
  "Affection Section",
  "Air Penguins",
  "Alice in Wonderland Maze",
  "Alice's Curious Labyrinth",
  "Alive! Dinosaur Encounter",
  "AMAZU: Treetop Adventure",
  "American Heritage Gallery",
  "Andy's Adventures Dinosaur Dig",
  "Animal Babies of Peterhof",
  "Animal Care at Conservation Station",
  "Animation Academy",
  "Aqua Team Playground",
  "Ariel's Playground",
  "Atlantis by SEA LIFE™",
  "Awesome Planet",
  "Beach Playground",
  "Beagle Scout Acres",
  "Betinho Carrero 2D",
  "Big's Garden",
  "Bijutsu-kan Gallery",
  "Black Bear Trail",
  "Breakers Bay",
  "Bruce's Shark World",
  "Build-a-Raft River (Water Park)",
  "Bumba's Playground",
  "Canada Far and Wide in Circle-Vision 360",
  "Carolina Harbor Shore Club",
  "Casa do Projeto Tamar",
  "Casey Jr. Splash 'N' Soak Station",
  "Castaway Creek",
  "Castelo das Nações",
  "Castle of Magical Dreams",
  "CBeebies Land Photo Studio",
  "Challenge Trails at Camp Discovery",
  "Chapéu e Bota Gigante",
  "Character Carrousel",
  "Chip 'n Dale's Treehouse",
  "Cinderella Castle",
  "Cinderella's Fairy Tale Hall",
  "Cinema 4D Experience: Prezzemolo e l'Enigma Svelato",
  "Coastal Currents",
  "Cypress Gardens",
  "Deep in Africa – Adventure Trail",
  "Detective Conan 4-D Live Show: Jewel Under the Starry Sky",
  "DinoPlay",
  "Discovery Arcade",
  "Discovery Island Trails",
  "Disney and Pixar Short Film Festival",
  "Donald's Duck Pond",
  "Dragon's Playhouse - Soft Play",
  "DUPLO® Little Dino Trail",
  "DUPLO® Playground",
  "Efteling Museum",
  "Enchanted Tales with Belle",
  "Entry to World of Frozen",
  "Esculturas Romero Britto",
  "Estação João Alves de Queiroz",
  "Fairy Tail Trail",
  "Fantasy Gardens",
  "Ferrari Land Gallery",
  "Festival Station",
  "Firehouse Fun Yard",
  "Flotation Station",
  "Fotos com a Turma do Madagascar",
  "Fotos com Betinho e Lully",
  "Fotos com Bob Esponja e sua turma",
  "Fotos com Megamente e Metro Man",
  "Fotos com Po do Kung Fu Panda",
  "Fotos com Shrek e sua Turma",
  "Fotos com Trolls",
  "Frontierland Playground",
  "Frontierland Shootin' Exposition",
  "Gallery of Arts and History",
  "Gallery of Football Stars",
  "Games of Pixar Pier",
  "Garden of Wonders",
  "Garden Tour",
  "GoofyCore at CommuniCore Hall",
  "Goofys How to Play Yard",
  "Gorilla Falls Exploration Trail",
  "Grandfather's Mansion",
  "Granny's Garden",
  "Great Moments with Mr. Lincoln",
  "Hampi Playground",
  "Haunted Hollow",
  "Heartlake Stepping Tones Fountain",
  "Heidi's Playground",
  "Hey Duggee’s Big Adventure Badge",
  "Hidden Hollow",
  "Hootie's Tree House",
  "Hootie’s Treehouse",
  "House of the Whispering Willows",
  "If I Ran The Zoo™",
  "ImageWorks - The \"What If\" Labs",
  "Imagination Station (Water Park)",
  "Impossible",
  "Indoor Play Area",
  "Iron Man Tech Showcase - Presented by Stark Industries",
  "Jessie's Roundup: A Rip-Roarin' Revue!",
  "JoJo & Gran Gran At Home",
  "Journey of Water, Inspired by Moana",
  "JUJUTSU KAISEN: The Real 4-D — Clock Tower of Recurrence",
  "Jurassic Park Discovery Center™",
  "Justin's House Pie-O-Matic Factory",
  "Kaanapali Kooler Lazy River",
  "Kidcot Fun Stops",
  "Kiddy Hawk Cove",
  "KidZville Station",
  "Kopiko Wai Winding River™",
  "Kozmo's Play Area",
  "Kung Fu Games",
  "Laberinto Blacksmith",
  "Lakeside Lagoon - Pool",
  "Lakeside Lagoon Pool",
  "LavaLand Playground",
  "Lazy Rider",
  "Lazy River",
  "LEGO ® Factory Tour",
  "LEGO® City Police Building Experience",
  "LEGO® City Police Station Maze",
  "LEGO® DUPLO® PEPPA PIG Playground",
  "LEGO® Factory",
  "LEGOLAND® ATLANTIS by SEA LIFE",
  "Liberty Arcade",
  "Lil' Pilots Playground",
  "Little Hooch Lazy River",
  "Lloyd's Laser Maze",
  "Madame Gazelle's Nature Trail",
  "Maharajah Jungle Trek",
  "Main Street Cinema",
  "Main Street Vehicles",
  "Maple Park Tree House",
  "Maple Park Treehouse",
  "Marvel Cave",
  "Maya's Playground",
  "Meet ‘Olu Mel at Duffy and Friends Play House",
  "Meet Ariel at Walt Disney Presents",
  "Meet CookieAnn at Duffy and Friends Play House",
  "Meet Disney Princesses at Royal Hall",
  "Meet Disney Stars at Red Carpet Dreams",
  "Meet Duffy at Duffy and Friends Play House",
  "Meet Edna Mode at the Edna Mode Experience",
  "Meet Gelatoni at Duffy and Friends Play House",
  "Meet LinaBell at Duffy and Friends Play House",
  "Meet Mickey Mouse",
  "Meet Olaf at Celebrity Spotlight",
  "Meet ShellieMay at Duffy and Friends Play House",
  "Meet StellaLou at Duffy and Friends Play House",
  "Meet&great Karlo and Karoline",
  "Memorial Beto Carrero",
  "Mexico Folk Art Gallery",
  "Mickey's House",
  "Mickey's House and Meet Mickey Mouse",
  "Mickey's PhilharMagic",
  "Minion Games",
  "Minnie's House",
  "Model Builder Experience",
  "Mountain Bay Cliffs",
  "Myrtle Turtle Beach",
  "Nature Way / Sensory Garden",
  "NERF Arcade!",
  "Oasis Exhibits",
  "Old Time Photo",
  "Otter Trotters",
  "Palais du Cinéma",
  "Panoramix Play Area",
  "Paradise River",
  "Penny Arcade",
  "Peppa & George Meet & Greet",
  "Peppa Pig's Treehouse",
  "Peppa's Pedal Bike Tour and George's Tricycle Trail",
  "Petit Chêne Play Area",
  "Pirate Galleon",
  "Pirate Playground",
  "Pirate's Lair on Tom Sawyer Island",
  "Pirates Landing",
  "Pixar Short Film Spotlight",
  "Planet Snoopy Construction Zone",
  "PLAYGROUND",
  "Plop's Garden",
  "Police Building Experience",
  "Ponte Pênsil",
  "Portal da Escuridão",
  "Project Tomorrow: Inventing the Wonders of the Future",
  "Psssht Station",
  "Pumphouse",
  "Pups Pier",
  "Rafts to Tarzan's Treehouse",
  "Rebecca Rabbit's Playground",
  "Redwood Creek Challenge Trail",
  "Reflections of China",
  "Rocket Factory",
  "Rosita's Harmony Hills",
  "Rubber Duckie Water Works",
  "Rubble & Rocky's Play Zone",
  "Run-A-Way River",
  "Runamukka Reef™",
  "Runaway River",
  "Rustler Roundup Shootin' Gallery",
  "Sanglier d'Or playground",
  "SeaBase Aquarium",
  "Seaside Splashworks",
  "SésamoAventura Station",
  "Sharkbait Reef by SEA LIFE",
  "Shipyard Playground",
  "Shrek’s 4-D Adventure™",
  "Sleeping Beauty Castle Walkthrough",
  "Soak'em Playground",
  "Something Special Sensory Garden",
  "Sorcerer's Workshop",
  "Spatiale Experience - Grand-Huit",
  "Spell Keeper",
  "Splash River",
  "Splash Station",
  "Sprayground",
  "Star Wars Launch Bay",
  "Stave Church Gallery",
  "Stepping Tones",
  "Stitch Encounter",
  "Sunset River",
  "Surf Club Harbor",
  "Swiss Family Treehouse",
  "Tarzan's Treehouse",
  "Taz’s Film Works",
  "TeAwa The Fearless River™",
  "Texas Town - Western Playground",
  "Texas Treehouse",
  "The Animal Farm",
  "The Animation Experience at Conservation Station",
  "The Bakery Tour",
  "The Disney Gallery",
  "The Gardens",
  "The Great LEGO® Reef",
  "The Magic Lamp Theater",
  "The Oasis Exhibits",
  "The Playground",
  "The Reef",
  "The Royal Reception Hall",
  "Thomas' Dokidoki Playground",
  "Tidal Wave Bay",
  "Timber Trail",
  "Tot Tiki Reef™",
  "TOXIC GARDEN",
  "Tree of Life",
  "Tree of Life Garden",
  "Treehouse Island",
  "Treetop Adventure",
  "Vacation Fun - An Original Animated Short with Mickey & Minnie",
  "Van Helsing's Factory",
  "Van Helsing’s Factory",
  "Vista Trail at Camp Discovery",
  "Walt Disney Presents",
  "Walt Disney's Carousel of Progress",
  "Walt Disney's Enchanted Tiki Room",
  "Water Garden",
  "Welcome to Starport: A Star Wars Encounter",
  "Westernland Shootin' Gallery",
  "White Water Bay",
  "Wickie Playground",
  "Wild West Photo Fun",
  "Wild West Water Works",
  "Wilderness Explorers",
  "Wildwater River",
  "Willy's Playground",
  "Woody’s Roundup",
  "WP - Carolina Harbor Shore Club",
  "Zoe's Tree House"
];
