export const GOLD_LIST = [
  " Labs",
  "123 Playground",
  "22 Egipt Zew Licznik",
  "23 Egipt Wew Licznik",
  "A Pirate's Adventure",
  "A Pirate's Adventure ~ Treasures of the Seven Seas",
  "AMAZU: Treetop Adventure",
  "Acme Fun Factory",
  "Additional Peppa Pig World Characters Meet & Greet",
  "Advanced Training Lab",
  "Adventure Isle",
  "Adventure Playground",
  "Adventure River",
  "Adventureland Treehouse inspired by Walt Disney’s Swiss Family Robinson",
  "Affection Section",
  "Air Penguins",
  "Alice in Wonderland Maze",
  "Alice's Curious Labyrinth",
  "Alive! Dinosaur Encounter",
  "American Heritage Gallery",
  "Andy's Adventures Dinosaur Dig",
  "Animal Babies of Peterhof",
  "Animal Care at Conservation Station",
  "Animation Academy",
  "Anton Pieck Plein",
  "Aqua Team Playground",
  "Archipel",
  "Arena of Football - Be Part of It!",
  "Ariel's Playground",
  "Atlantis by SEA LIFE™",
  "Awesome Planet",
  "Badhuys indoor splash pool",
  "Ball House",
  "Bamboozle Bay Pool",
  "Bao Haus",
  "Beach Playground",
  "Beagle Scout Acres",
  "Betinho Carrero 2D",
  "Big's Garden",
  "Bijutsu-kan Gallery",
  "Black Bear Trail",
  "Boogie Bay Pool",
  "Breakers Bay",
  "Bruce's Shark World",
  "Build-a-Raft River (Water Park)",
  "Bumba's Playground",
  "Butterfly Bayou",
  "CBeebies Land Photo Studio",
  "Canada Far and Wide in Circle-Vision 360",
  "Canopy Capers",
  "Carolina Harbor Shore Club",
  "Casa do Projeto Tamar",
  "Casey Jr. Splash 'N' Soak Station",
  "Castaway Creek",
  "Castelo das Nações",
  "Castle of Magical Dreams",
  "Challenge Trails at Camp Discovery",
  "Chapéu e Bota Gigante",
  "Character Carrousel",
  "Chip 'n Dale's Treehouse",
  "Cinderella Castle",
  "Cinderella's Fairy Tale Hall",
  "Cinema 4D Experience: Prezzemolo e l'Enigma Svelato",
  "Coastal Currents",
  "Comal Cove",
  "Cypress Gardens",
  "DUPLO® Little Dino Trail",
  "DUPLO® Playground",
  "Deep in Africa – Adventure Trail",
  "Deluge",
  "DinoPlay",
  "Diorama",
  "Discovery Arcade",
  "Discovery Island Trails",
  "Disney and Pixar Short Film Festival",
  "Donald's Duck Pond",
  "Dragon's Lair Pool",
  "Dragon's Playhouse - Soft Play",
  "Droomvlucht VR",
  "Efteling Museum",
  "Enchanted Tales with Belle",
  "Esculturas Romero Britto",
  "Estação João Alves de Queiroz",
  "Fabula",
  "Fairy Tail Trail",
  "Fairytale Forest",
  "Fantasy Gardens",
  "Ferrari Land Gallery",
  "Festival Station",
  "Firehouse Fun Yard",
  "Flotation Station",
  "Fortune Market",
  "Fotos com Betinho e Lully",
  "Fotos com Bob Esponja e sua turma",
  "Fotos com Megamente e Metro Man",
  "Fotos com Po do Kung Fu Panda",
  "Fotos com Shrek e sua Turma",
  "Fotos com Trolls",
  "Fotos com a Turma do Madagascar",
  "Frontierland Playground",
  "Frontierland Shootin' Exposition",
  "Fur-Bidden Forest",
  "Gallery of Arts and History",
  "Gallery of Football Stars",
  "Game Adventure",
  "Game Pia",
  "Games of Pixar Pier",
  "Garden Tour",
  "Garden of Wonders",
  "Goofy's How-to-Play Yard",
  "GoofyCore at CommuniCore Hall",
  "Goofys How to Play Yard",
  "Gorilla Falls Exploration Trail",
  "Grandfather's Mansion",
  "Granny's Garden",
  "Great Moments with Mr. Lincoln",
  "Hampi Playground",
  "Han's Hideout",
  "Hang Ten Harbor Activity Pool",
  "Haunted Hollow",
  "Heartlake Stepping Tones Fountain",
  "Heidi's Playground",
  "Hey Duggee’s Big Adventure Badge",
  "Hidden Hollow",
  "Hootie's Tree House",
  "Hootie’s Treehouse",
  "House of the Whispering Willows",
  "If I Ran The Zoo™",
  "ImageWorks - The ",
  "Imagination Station (Water Park)",
  "Impossible",
  "Indoor Play Area",
  "Iron Man Tech Showcase - Presented by Stark Industries",
  "JUJUTSU KAISEN: The Real 4-D — Clock Tower of Recurrence",
  "Jessie's Roundup: A Rip-Roarin' Revue!",
  "JoJo & Gran Gran At Home",
  "Journey of Water, Inspired by Moana",
  "Jurassic Park Discovery Center™",
  "Justin's House Pie-O-Matic Factory",
  "Kaanapali Kooler Lazy River",
  "KidZville Station",
  "Kidcot Fun Stops",
  "Kiddie Coast",
  "Kiddy Hawk Cove",
  "Kids Cove",
  "Kinderhaven",
  "Kindervreugd",
  "Kleuterhof",
  "Kopiko Wai Winding River™",
  "Kozmo's Play Area",
  "Kristal Cove",
  "Kristal River",
  "Kung Fu Games",
  "LEGO ® Factory Tour",
  "LEGOLAND® ATLANTIS by SEA LIFE",
  "LEGO® City Police Building Experience",
  "LEGO® City Police Station Maze",
  "LEGO® DUPLO® PEPPA PIG Playground",
  "LEGO® Factory",
  "La Cabane des Robinson",
  "La Tanière du Dragon",
  "Laberinto Blacksmith",
  "Lagoon Activity Pool",
  "Lagoon Kids' Area",
  "Lagoon Pool",
  "Lakeside Lagoon - Pool",
  "Lakeside Lagoon Pool",
  "Lava Lagoon",
  "LavaLand Playground",
  "Lazy Rider",
  "Lazy River",
  "Le Passage Enchanté d'Aladdin",
  "Lenny's Magic School",
  "Les Mystères du Nautilus",
  "Liberty Arcade",
  "Lil' Pilots Playground",
  "Little Hooch Lazy River",
  "Lloyd's Laser Maze",
  "Lolipop Farm",
  "Lollipop Lagoon",
  "MEMORY CARNIVAL",
  "Madame Gazelle's Nature Trail",
  "Magic Cookie House",
  "Maharajah Jungle Trek",
  "Main Street Cinema",
  "Main Street Vehicles",
  "Maple Park Tree House",
  "Maple Park Treehouse",
  "Marvel Cave",
  "Maya's Playground",
  "Meet Ariel at Walt Disney Presents",
  "Meet CookieAnn at Duffy and Friends Play House",
  "Meet Disney Princesses at Royal Hall",
  "Meet Disney Stars at Red Carpet Dreams",
  "Meet Duffy at Duffy and Friends Play House",
  "Meet Edna Mode at the Edna Mode Experience",
  "Meet Gelatoni at Duffy and Friends Play House",
  "Meet LinaBell at Duffy and Friends Play House",
  "Meet Mickey Mouse",
  "Meet Olaf at Celebrity Spotlight",
  "Meet ShellieMay at Duffy and Friends Play House",
  "Meet StellaLou at Duffy and Friends Play House",
  "Meet ‘Olu Mel at Duffy and Friends Play House",
  "Meet&great Karlo and Karoline",
  "Memorial Beto Carrero",
  "Mexico Folk Art Gallery",
  "Mickey's House",
  "Mickey's House and Meet Mickey Mouse",
  "Mickey's PhilharMagic",
  "Minion Games",
  "Minnie's House",
  "Model Builder Experience",
  "Mountain Bay Cliffs",
  "Myrtle Turtle Beach",
  "NERF Arcade!",
  "Nature Way / Sensory Garden",
  "Nest!",
  "Oasis Exhibits",
  "Obsessive House",
  "Old Time Photo",
  "Opera House - Walt Disney - A Magical Life",
  "Otter Trotters",
  "PLAYGROUND",
  "Palais du Cinéma",
  "Panda 2nd House",
  "Panda World",
  "Panoramix Play Area",
  "Paradise River",
  "Penny Arcade",
  "Peppa & George Meet & Greet",
  "Peppa Pig's Treehouse",
  "Peppa's Pedal Bike Tour and George's Tricycle Trail",
  "Petit Chêne Play Area",
  "Pirate Galleon",
  "Pirate Playground",
  "Pirate's Lair on Tom Sawyer Island",
  "Pirates Landing",
  "Pirates' Beach",
  "Pixar Short Film Spotlight",
  "Planet Snoopy Construction Zone",
  "Play Yard",
  "Plop's Garden",
  "Police Building Experience",
  "Ponte Pênsil",
  "Portal da Escuridão",
  "Princess Pavilion",
  "Project Tomorrow: Inventing the Wonders of the Future",
  "Psssht Station",
  "Pumphouse",
  "Pups Pier",
  "Rafts to Tarzan's Treehouse",
  "Rebecca Rabbit's Playground",
  "Redwood Creek Challenge Trail",
  "Reflections of China",
  "River Bend Pool",
  "Rocket Factory",
  "Room on the Broom - A Magical Journey",
  "Rosita's Harmony Hills",
  "Rubber Duckie Water Works",
  "Rubble & Rocky's Play Zone",
  "Run-A-Way River",
  "Runamukka Reef™",
  "Runaway River",
  "Rustler Roundup Shootin' Gallery",
  "Sanglier d'Or playground",
  "Scary Loft",
  "Sea Creature Cove",
  "SeaBase Aquarium",
  "Seaside Splashworks",
  "Sharkbait Reef by SEA LIFE",
  "Shipyard Playground",
  "Shrek’s 4-D Adventure™",
  "Sleeping Beauty Castle Walkthrough",
  "Snoopy's Cloud Climbers",
  "Soak'em Playground",
  "Something Special Sensory Garden",
  "Sorcerer's Workshop",
  "Space Tour (4D Attraction)",
  "Spatiale Experience - Grand-Huit",
  "Spell Keeper",
  "Splash River",
  "Splash Station",
  "Spooky Fun House",
  "Sprayground",
  "Star Wars Launch Bay",
  "Stave Church Gallery",
  "Stepping Tones",
  "Stitch Encounter",
  "Sunset River",
  "Surf Club Harbor",
  "Swiss Family Treehouse",
  "SésamoAventura Station",
  "TOXIC GARDEN",
  "Tarzan's Treehouse",
  "Taz’s Film Works",
  "TeAwa The Fearless River™",
  "Texas Town - Western Playground",
  "Texas Treehouse",
  "The Animal Farm",
  "The Animation Experience at Conservation Station",
  "The Bakery Tour",
  "The Beach Wave Pool",
  "The Disney Gallery",
  "The Gardens",
  "The Great LEGO® Reef",
  "The Magic Lamp Theater",
  "The Oasis Exhibits",
  "The Playground",
  "The Reef",
  "The Royal Reception Hall",
  "Thomas' Dokidoki Playground",
  "Tidal Wave Bay",
  "Timber Trail",
  "Torrent River",
  "Tot Tiki Reef™",
  "Tree of Life",
  "Tree of Life Garden",
  "Treehouse Island",
  "Treetop Adventure",
  "Vacation Fun - An Original Animated Short with Mickey & Minnie",
  "Van Helsing's Factory",
  "Van Helsing’s Factory",
  "Vista Trail at Camp Discovery",
  "Volk van Laaf",
  "WP - Carolina Harbor Shore Club",
  "Walt Disney - A Magical Life",
  "Walt Disney Presents",
  "Walt Disney's Carousel of Progress",
  "Walt Disney's Enchanted Tiki Room",
  "Water Garden",
  "Wave Pool",
  "Welcome to Starport: A Star Wars Encounter",
  "Westernland Shootin' Gallery",
  "White Water Bay",
  "Wickie Playground",
  "Wild West Photo Fun",
  "Wild West Water Works",
  "Wilderness Explorers",
  "Wildwater Cove",
  "Wildwater River",
  "Willy's Playground",
  "Woody’s Roundup",
  "Wunder Pool",
  "Zoe's Tree House",
  "monimo-RUSH"
];
