export const GOLD_LIST = [
  " Labs",
  "123 Playground",
  "22 Egipt Zew Licznik",
  "23 Egipt Wew Licznik",
  "A Pirate's Adventure",
  "A Pirate's Adventure ~ Treasures of the Seven Seas",
  "Acme Fun Factory",
  "Additional Peppa Pig World Characters Meet & Greet",
  "Advanced Training Lab",
  "Adventure Isle",
  "Adventure Junction",
  "Adventure Playground",
  "Adventure River",
  "Adventureland Treehouse inspired by Walt Disney’s Swiss Family Robinson",
  "Affection Section",
  "Air Penguins",
  "Alice in Wonderland Maze",
  "Alice's Curious Labyrinth",
  "Alive! Dinosaur Encounter",
  "Allianz Arena",
  "AMAZU: Treetop Adventure",
  "American Heritage Gallery",
  "Andy's Adventures Dinosaur Dig",
  "Animal Babies of Peterhof",
  "Animal Care at Conservation Station",
  "Animal Treasure Island",
  "Animation Academy",
  "Anton Pieck Plein",
  "Aqua Team Playground",
  "Archipel",
  "Arena of Football - Be Part of It!",
  "Ariel's Playground",
  "Atlantis by SEA LIFE™",
  "Attention Menhir !",
  "Awesome Planet",
  "Badhuys indoor splash pool",
  "Baja Bends",
  "Ball House",
  "Bamboozle Bay Pool",
  "Bao Haus",
  "Barnens paradis",
  "Barrel of Fun",
  "Bayside Pier",
  "Beach House",
  "Beach Party",
  "Beach Playground",
  "Beagle Scout Acres",
  "Become Iron Man at the Marvel Universe",
  "Berlin",
  "Berliner Eislaufen",
  "Betinho Carrero 2D",
  "Big's Garden",
  "Bijutsu-kan Gallery",
  "Black Bear Trail",
  "Boogie Bay Pool",
  "Boogie Beach",
  "Breakers Bay",
  "Breakwater Bay",
  "Bricktopia Lounge",
  "Bruce's Shark World",
  "Build & Test",
  "Build a Boat",
  "Build and Test",
  "Build-a-Boat (Water Park)",
  "Build-a-Raft River (Water Park)",
  "Builders Guild",
  "Bumba's Playground",
  "Bushållplatsen",
  "Butterfly Bayou",
  "Camp Duck Amuck Fun Fort",
  "Camp Jurassic",
  "Canada Far and Wide in Circle-Vision 360",
  "Canopy Capers",
  "Carolina Harbor Shore Club",
  "Casa do Projeto Tamar",
  "Casey Jr. Splash 'N' Soak Station",
  "Castaway Camp",
  "Castaway Cove",
  "Castaway Creek",
  "Castelo das Nações",
  "Castle of Magical Dreams",
  "CBeebies Land Photo Studio",
  "Cedar Creek",
  "Challenge Trails at Camp Discovery",
  "Chapéu e Bota Gigante",
  "Character Carrousel",
  "Chip 'n Dale's Treehouse",
  "Cinderella Castle",
  "Cinderella's Fairy Tale Hall",
  "Cinema 4D Experience: Prezzemolo e l'Enigma Svelato",
  "Citadel Thrills and Skills Land",
  "Coastal Currents",
  "Coconut Cove",
  "Cole's Rock Climb",
  "Cole's Rock Climbing",
  "Cole's Rock Climbing Wall",
  "Comal Cove",
  "Commotion Ocean",
  "Creation Zone",
  "Creative Jungle",
  "CreaZone",
  "Crime Alley: Night of Chaos",
  "Crocodile Isle Wave Pool",
  "Cypress Gardens",
  "Deep in Africa – Adventure Trail",
  "Deluge",
  "Detective Conan: The World",
  "DinoPlay",
  "Diorama",
  "Discovery Arcade",
  "Discovery Island Trails",
  "Disney and Pixar Short Film Festival",
  "Donald's Duck Pond",
  "Dragon's Lair Pool",
  "Dragon's Playhouse - Soft Play",
  "Drench Towers",
  "Droomvlucht VR",
  "Duffy and Friends Play House",
  "DUPLO® Little Dino Trail",
  "DUPLO® Play",
  "DUPLO® Play - Ninjago Dojo",
  "DUPLO® Play - Surfs Up",
  "DUPLO® Playground",
  "DUPLO® Splash Safari (Water Park)",
  "DUPLO® Tot Spot",
  "DUPLO® Valley Schoolhouse",
  "East Coast Waterworks",
  "Efteling Museum",
  "Eiffel Tower",
  "El Árbol Mágico",
  "El Huerto Encantado",
  "El Secreto de los Mayas",
  "El Taller de Papá Noel",
  "Enchanted Tales with Belle",
  "Esculturas Romero Britto",
  "Estação João Alves de Queiroz",
  "Fabula",
  "Fairy Tail Trail",
  "Fairy Tale Forest",
  "Fairytale Forest",
  "Family Lagoon",
  "Fantasy Gardens",
  "Fascination",
  "Ferrari Land Gallery",
  "Festival Station",
  "Firehouse Fun Yard",
  "FireHouse Play Place",
  "Flotation Station",
  "Fortress Explorations",
  "Fortune Market",
  "Fotos com a Turma do Madagascar",
  "Fotos com Betinho e Lully",
  "Fotos com Bob Esponja e sua turma",
  "Fotos com Megamente e Metro Man",
  "Fotos com Po do Kung Fu Panda",
  "Fotos com Shrek e sua Turma",
  "Fotos com Trolls",
  "Frankfurt",
  "Frontierland Playground",
  "Frontierland Shootin' Exposition",
  "Fun Fair",
  "Fur-Bidden Forest",
  "G-Force Test Facility",
  "Gallery of Arts and History",
  "Gallery of Football Stars",
  "Game Adventure",
  "Game Pia",
  "Games of Pixar Pier",
  "Gaming Zone powered by Nintendo",
  "Garage",
  "Garden of Wonders",
  "Garden Tour",
  "George's Fort",
  "Geyser Gulch",
  "Ghost – The Haunted House",
  "Gold Panning",
  "Goofy's How-to-Play Yard",
  "GoofyCore at CommuniCore Hall",
  "Goofys How to Play Yard",
  "Gorilla Falls Exploration Trail",
  "Grandfather's Mansion",
  "Grandpa Pig's Greenhouse",
  "Granny's Garden",
  "Great Lakes Cove",
  "Great Moments with Mr. Lincoln",
  "Gremmie Lagoon",
  "Half-Pint Paradise",
  "Hamburg Harbour",
  "Hampi Playground",
  "Han's Hideout",
  "Hang Ten Harbor Activity Pool",
  "Haunted Hollow",
  "Heartlake Stepping Tones Fountain",
  "Heidi's Playground",
  "Hey Duggee’s Big Adventure Badge",
  "Hidden Hollow",
  "High Ropes Course in Holiday Village",
  "Hook's Lagoon",
  "Hootie's Tree House",
  "Hootie’s Treehouse",
  "House of the Whispering Willows",
  "If I Ran The Zoo™",
  "ImageWorks - The ",
  "ImageWorks - The \"What If\" Labs",
  "Imagination Station (Water Park)",
  "Imagination Zone",
  "Impossible",
  "Indoor Play Area",
  "Iron Man Tech Showcase - Presented by Stark Industries",
  "IT Experience",
  "Jay's Lightning Drill",
  "Jessie's Roundup: A Rip-Roarin' Revue!",
  "JoJo & Gran Gran At Home",
  "Joker Soaker (Water Park)",
  "Journey of Water, Inspired by Moana",
  "Journey to the Forbidden Chamber",
  "JUJUTSU KAISEN: The Real 4-D — Clock Tower of Recurrence",
  "Jumanji The Labyrinth",
  "Junior Astronaut Training Zone",
  "Junior Explorers Camp",
  "Jurassic Park Discovery Center™",
  "Justin's House Pie-O-Matic Factory",
  "Kaanapali Kooler Lazy River",
  "Kai's Balancers",
  "Kai's Fire Spinners",
  "Kai's Spinners",
  "Kidcot Fun Stops",
  "Kiddie Coast",
  "Kiddy Hawk Cove",
  "Kids Cove",
  "KidZville Station",
  "Kinderhaven",
  "Kindervreugd",
  "Kleuterhof",
  "Kopiko Wai Winding River™",
  "Kozmo's Play Area",
  "Kristal Cove",
  "Kristal River",
  "Kung Fu Games",
  "L'Albero di Prezzemolo",
  "L'Aventure Astérix",
  "La Cabane des Robinson",
  "La Monja",
  "La Tanière du Dragon",
  "Laberinto Blacksmith",
  "Lagoon Activity Pool",
  "Lagoon Kids' Area",
  "Lagoon Pool",
  "Lakeside Lagoon - Pool",
  "Lakeside Lagoon Pool",
  "Lakeslide Landing",
  "Lava Lagoon",
  "LavaLand Playground",
  "Lazer Command",
  "Lazy Rider",
  "Lazy River",
  "Le Passage Enchanté d'Aladdin",
  "LEGO ® Factory Tour",
  "LEGO® City Police Building Experience",
  "LEGO® City Police Station Maze",
  "LEGO® Creative Workshop",
  "LEGO® DUPLO® PEPPA PIG Playground",
  "LEGO® Factory",
  "LEGO® Ferrari Build & Race Experience",
  "LEGO® Fortnite®",
  "LEGO® Friends Bedrooms",
  "LEGO® NINJAGO® WORLD Toddler Area",
  "LEGO® Wave Pool (Water Park)",
  "LEGOLAND® ATLANTIS by SEA LIFE",
  "LEGOLAND® Bowling Center",
  "Lemmys Lagoon",
  "Lenny's Magic School",
  "Les Mystères du Nautilus",
  "Liberty Arcade",
  "Lighthouse Landing",
  "Lights Camera Action!",
  "Liki Tikis",
  "Lil' Barefoot Beach",
  "Lil' Pilots Playground",
  "Lily Pad Walk",
  "Little Hooch Lazy River",
  "Lloyd's Laser Maze",
  "Lolipop Farm",
  "Lollipop Lagoon",
  "Lookout Lagoon",
  "Looney Tunes Adventure Camp",
  "Looney Tunes Lodge",
  "Los Reyes Magos",
  "Madame Gazelle's Nature Trail",
  "Magic Cookie House",
  "Maharajah Jungle Trek",
  "Main Street Cinema",
  "Main Street Vehicles",
  "Maple Park Tree House",
  "Maple Park Treehouse",
  "Marvel Cave",
  "Marvel Universe",
  "Maya's Playground",
  "Meet ‘Olu Mel at Duffy and Friends Play House",
  "Meet Ariel at Walt Disney Presents",
  "Meet CookieAnn at Duffy and Friends Play House",
  "Meet Disney Princesses at Royal Hall",
  "Meet Disney Stars at Red Carpet Dreams",
  "Meet Duffy at Duffy and Friends Play House",
  "Meet Edna Mode at the Edna Mode Experience",
  "Meet Gelatoni at Duffy and Friends Play House",
  "Meet LinaBell at Duffy and Friends Play House",
  "Meet Mickey Mouse",
  "Meet Olaf at Celebrity Spotlight",
  "Meet ShellieMay at Duffy and Friends Play House",
  "Meet StellaLou at Duffy and Friends Play House",
  "Meet&great Karlo and Karoline",
  "Memorial Beto Carrero",
  "MEMORY CARNIVAL",
  "Mexico Folk Art Gallery",
  "Mickey's House",
  "Mickey's House and Meet Mickey Mouse",
  "Mickey's PhilharMagic",
  "Mine Sluice",
  "Mini Golf",
  "Mini Monster Clubhouse",
  "Miniland",
  "MINILAND USA",
  "Minion Games",
  "Minnie's House",
  "Model Builder Experience",
  "monimo-RUSH",
  "Monster Clubhouse",
  "Mountain Bay Cliffs",
  "Muddy Puddles Splash Pad",
  "Myrtle Turtle Beach",
  "Mystic Point Freight Depot",
  "Nature Way / Sensory Garden",
  "NERF Arcade!",
  "Nest!",
  "Neuschwanstein Castle",
  "Oasis Exhibits",
  "Obsessive House",
  "Old Time Photo",
  "Ollivanders™ Experience in Diagon Alley™",
  "Opera House - Walt Disney - A Magical Life",
  "Otter Trotters",
  "Palais du Cinéma",
  "Panda 2nd House",
  "Panda World",
  "Panoramix Play Area",
  "Paradise River",
  "PEANUTS™ Playhouse",
  "Penny Arcade",
  "Peppa & George Meet & Greet",
  "Peppa Pig Land - La Casa di Peppa Pig",
  "Peppa Pig's Treehouse",
  "Peppa's Pedal Bike Tour and George's Tricycle Trail",
  "PEPPAS HOUSE",
  "Petit Chêne Play Area",
  "Pharaoh's Revenge",
  "Pirate Galleon",
  "Pirate Golf in Holiday Village",
  "Pirate Island Sand Play",
  "Pirate Playground",
  "Pirate's Lair on Tom Sawyer Island",
  "Pirates Landing",
  "Pirates' Beach",
  "Pixar Short Film Spotlight",
  "Planet Snoopy Construction Zone",
  "Play Yard",
  "PLAYGROUND",
  "Playhouse in the Woods",
  "Playland",
  "Plop's Garden",
  "Po's Kung Fu Training Camp",
  "Pole Position Challenge",
  "Police Building Experience",
  "Ponte Pênsil",
  "Portal da Escuridão",
  "Power-Up Band™ Key Challenges",
  "Prezzemolo Land",
  "Prezzemolo Magic Village",
  "Princess Pavilion",
  "Project Nightmare",
  "Project Tomorrow: Inventing the Wonders of the Future",
  "Psssht Station",
  "Puka Uli Lagoon™",
  "Pumphouse",
  "Pups Pier",
  "Rafts to Tarzan's Treehouse",
  "Rainbow Design Studio",
  "Rebecca Rabbit's Playground",
  "Rebuild the World - Planet LEGOLAND",
  "Rebuild the World: Planet LEGOLAND®",
  "Redwood Creek Challenge Trail",
  "Reflections of China",
  "River Bend Pool",
  "Rock Wall Climbing Challenge",
  "Rocket Factory",
  "Rocky Point Mini-Golf",
  "Room on the Broom - A Magical Journey",
  "Rosita's Harmony Hills",
  "Rubber Duckie Water Works",
  "Rubble & Rocky's Play Zone",
  "Rudolph the Red-Nosed Reindeer Experience",
  "Run-A-Way River",
  "Runamukka Reef™",
  "Runaway River",
  "Rustler Roundup Shootin' Gallery",
  "Sand Dune Lagoon",
  "Sanglier d'Or playground",
  "Scary Loft",
  "Sea Creature Cove",
  "SeaBase Aquarium",
  "Seaside Splashworks",
  "SésamoAventura Station",
  "Sharkbait Reef by SEA LIFE",
  "Shipwreck Shore",
  "Shipyard Playground",
  "Shoreline Sprayground",
  "Shrek’s 4-D Adventure™",
  "Siren's Revenge",
  "Sleeping Beauty Castle Walkthrough",
  "Snoopy's Cloud Climbers",
  "Snuffy's Slides",
  "Soak'em Playground",
  "Something Special Sensory Garden",
  "Sorcerer's Workshop",
  "Space Chat With Stitch",
  "Space Tour (4D Attraction)",
  "Spatiale Experience - Grand-Huit",
  "Spell Keeper",
  "Splash Island",
  "Splash Landing",
  "Splash River",
  "Splash Safari",
  "Splash Station",
  "SplasH2O",
  "Spooky Fun House",
  "Sprayground",
  "Star Wars Launch Bay",
  "Stave Church Gallery",
  "Steam Town Carnival Games",
  "Stepping Tones",
  "Stitch Encounter",
  "Sunset River",
  "Surf Club Harbor",
  "Swabian Village",
  "Swiss Family Treehouse",
  "Switzerland",
  "Tarzan's Treehouse",
  "Taz’s Film Works",
  "TeAwa The Fearless River™",
  "Temple Building Fun",
  "Templo del Fuego",
  "Texas Town - Western Playground",
  "Texas Treehouse",
  "The Animal Farm",
  "The Animation Experience at Conservation Station",
  "The Bakery Tour",
  "The Beach Wave Pool",
  "The Disney Gallery",
  "The Enchanted Greenhouse",
  "The Gardens",
  "The Great LEGO® Reef",
  "The LEGOLAND® Story",
  "The Leonardo Challenge",
  "The Magic Lamp Theater",
  "The Netherlands",
  "The Oasis Exhibits",
  "The Playground",
  "The Reef",
  "The Royal Reception Hall",
  "The Secret Chamber of Amset-ra",
  "The Shore",
  "The Wharf",
  "Thomas' Dokidoki Playground",
  "Tidal Wave Bay",
  "Timber Trail",
  "Toon Park",
  "Torrent River",
  "Tot Tiki Reef™",
  "TOXIC GARDEN",
  "Tree of Life",
  "Tree of Life Garden",
  "Treehouse Island",
  "Treetop Adventure",
  "TRON Realm, Chevrolet Digital Challenge",
  "Turtle Talk",
  "ULUM: El despertar jurásico",
  "Vacation Fun - An Original Animated Short with Mickey & Minnie",
  "Van Helsing's Factory",
  "Van Helsing’s Factory",
  "Venice",
  "Vista Trail at Camp Discovery",
  "Volk van Laaf",
  "Walt Disney - A Magical Life",
  "Walt Disney Presents",
  "Walt Disney's Carousel of Progress",
  "Walt Disney's Enchanted Tiki Room",
  "Water Garden",
  "Waterin Hole",
  "WaterWorks",
  "Waturi Beach",
  "Wave Pool",
  "Welcome to Starport: A Star Wars Encounter",
  "Westernland Shootin' Gallery",
  "White Water Bay",
  "Wickie Playground",
  "Wild West Photo Fun",
  "Wild West Water Works",
  "Wilderness Explorers",
  "Wildwater Cove",
  "Wildwater River",
  "Willy's Playground",
  "Woody’s Roundup",
  "Workshop",
  "WP - Carolina Harbor Shore Club",
  "Wunder Pool",
  "Zane's Temple Build",
  "Zoe's Tree House"
];
