export const VERIFIED_SHOWS = [
  "4D Cinema",
  "Beauty and the Beast – Live on Stage",
  "Beauty and the Beast Sing-Along",
  "Beauty and the Beast-Live on Stage",
  "Big Fun Showtime",
  "Bluey’s Best Day Ever! at Fantasyland Theatre",
  "Celebration of Festival of the Lion King",
  "Cinema",
  "Country Bear Musical Jamboree",
  "Country Bear Theater",
  "Daffy Duck Stars on Parade",
  "Detective Conan 4-D Live Show: Jewel Under the Starry Sky",
  "Disney Junior Play & Dance!",
  "Disney Movie Magic",
  "Disney's Enchanted Tiki Room",
  "Disney’s Not-So-Spooky Spectacular",
  "Dolphin Adventures",
  "Dolphin Adventures - ASL Saturday",
  "Dolphin Adventures - Located in Dolphin Stadium",
  "Excalibur",
  "Fantasmic!",
  "Feathered Friends in Flight!",
  "Festival of the Lion King",
  "Finding Nemo: The Big Blue... and Beyond!",
  "Finding Nemo: The Musical",
  "For the First Time in Forever: A Frozen Sing-Along Celebration",
  "GHOSTBUSTERS 5D",
  "Hot Wheels Epic Show",
  "Impressions de France",
  "Indiana Jones™ Epic Stunt Spectacular!",
  "It's a small world Holiday",
  "It's Tough to be a Bug!",
  "LEGO® Studios 4D",
  "Lightning McQueen's Racing Academy",
  "Madagascar Circus Show",
  "Mermaid Lagoon Theater",
  "Mickey's Magical Friendship Faire",
  "Mr. Potato's Showtime Arena",
  "Muppet*Vision 3D",
  "No Ritmo de Trolls",
  "O Sonho do Cowboy!",
  "Orca Encounter",
  "Orca Encounter - ASL Saturday",
  "Orca Encounter - Located in Orca Stadium",
  "Palace 4D Cinema",
  "Piggy Parade",
  "Pony Parade",
  "Pyramid Cinema 7 D",
  "Ready Player One 4D Experience | Age Rating 12A",
  "Sea Lions: Flippers, Facts & Fun",
  "Sea Lions: Flippers, Facts & Fun - ASL Saturday",
  "Sesame Street 4-D Movie Magic™",
  "The American Adventure",
  "The Animation Experience",
  "The Furchester Hotel Live Show",
  "The Hall of Presidents",
  "Tree of Life Awakenings",
  "Turtle Talk with Crush",
  "Turtle Talk With Crush",
  "Unhallowed 2 Show",
  "Vacation Fun",
  "Voices of Liberty",
  "Wonderful World of Animation"
];
