export const VERIFIED_SHOWS = [
  "4D Cinema",
  "Beauty and the Beast – Live on Stage",
  "Beauty and the Beast-Live on Stage",
  "Big Fun Showtime",
  "Celebration of Festival of the Lion King",
  "Cinema",
  "Daffy Duck Stars on Parade",
  "Disney Junior Play & Dance!",
  "Disney Movie Magic",
  "Disney's Enchanted Tiki Room",
  "Disney’s Not-So-Spooky Spectacular",
  "Dolphin Adventures",
  "Dolphin Adventures - ASL Saturday",
  "Dolphin Adventures - Located in Dolphin Stadium",
  "Excalibur",
  "Fantasmic!",
  "Feathered Friends in Flight!",
  "Festival of the Lion King",
  "Finding Nemo: The Big Blue... and Beyond!",
  "Finding Nemo: The Musical",
  "GHOSTBUSTERS 5D",
  "Hot Wheels Epic Show",
  "Indiana Jones™ Epic Stunt Spectacular!",
  "It's a small world Holiday",
  "It's Tough to be a Bug!",
  "LEGO® Studios 4D",
  "Lightning McQueen's Racing Academy",
  "Madagascar Circus Show",
  "Mickey's Magical Friendship Faire",
  "Muppet*Vision 3D",
  "O Sonho do Cowboy!",
  "Orca Encounter",
  "Orca Encounter - ASL Saturday",
  "Orca Encounter - Located in Orca Stadium",
  "Palace 4D Cinema",
  "Piggy Parade",
  "Pony Parade",
  "Pyramid Cinema 7 D",
  "Sea Lions: Flippers, Facts & Fun",
  "Sea Lions: Flippers, Facts & Fun - ASL Saturday",
  "Sesame Street 4-D Movie Magic™",
  "The Animation Experience",
  "The Furchester Hotel Live Show",
  "Tree of Life Awakenings",
  "Vacation Fun",
  "Voices of Liberty",
  "Wonderful World of Animation"
];
